apiVersion: v1
kind: ReplicationController
metadata:
  namespace: quobyte
  name: registry
spec:
  replicas: 3
  template:
    metadata:
      labels:
        role: registry
        version: 1.2.16
      name: registry-bootstrap
      namespace: quobyte
    spec:
      containers:
        - name: quobyte-registry
          image: quay.io/quobyte/quobyte-server:1.2.16
          securityContext:
            privileged: true
          env:
            - name: QUOBYTE_SERVICE
              value: registry
            - name: QUOBYTE_RPC_PORT
              value: "7866"
            - name: QUOBYTE_HTTP_PORT
              value: "7876"
            - name: QUOBYTE_REGISTRY
              value: registry
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: rpc-tcp
              containerPort: 7866
              protocol: TCP
            - name: rpc-udp
              containerPort: 7866
              protocol: UDP
            - name: http
              containerPort: 7876
              protocol: TCP
          volumeMounts:
            - name: devices
              mountPath: /devices/dev1
          command:
            - /bin/bash
            - -xec
            - |
              sed "s/.*MIN_MEM_REGISTRY=.*/MIN_MEM_REGISTRY=64m/" -i /etc/default/quobyte
              sed "s/.*MAX_MEM_REGISTRY=.*/MAX_MEM_REGISTRY=450m/" -i /etc/default/quobyte
              if [ ! -f /devices/dev1/QUOBYTE_DEV_SETUP ]; then
                mkdir -p /devices/dev1
                cat >/devices/dev1/QUOBYTE_DEV_SETUP <<EOF
              device.serial=${POD_NAME}-$(uuidgen)
              device.model=Kubernetes-emptyDir
              device.type=DIR_DEVICE
              EOF
              fi
              exec /bin/bash -x /opt/main.sh
          resources:
            limits:
              memory: "512Mi"
              cpu: "100m"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "-xc", "qmgmt -u api registry remove $(grep device.id= /devices/dev1/QUOBYTE_DEV_ID | cut -d= -f2)"]
          readinessProbe:
            timeoutSeconds: 5
            httpGet:
              port: 7876
              path: /
      imagePullSecrets:
        - name: dockercfg
      volumes:
      - name: devices
        emptyDir:
