apiVersion: quobyte.com/v1
kind: QuobyteService
metadata:
  name: quobyte-services
spec:
  registry:
    daemonSetName: registry
    nodes:
      - node1
  metadata:
    daemonSetName: metadata
    nodes:
      - node1
      - node2
      - node3
      - node4
  data:
    daemonSetName: data
    nodes:
      - node1
      - node2
      - node3
      - node4
